<?php

namespace WCS\CoavBundle\Repository;

/**
 * FlightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlightRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLastFlights()
    {
        $qb = $this
                ->createQueryBuilder('f')
                ->orderBy('f.takeOffTime', 'ASC')
                ->setMaxResults(3)
                ->getQuery();
        return $qb->getResult();
    }

}
