<?php

namespace WCS\CoavBundle\Repository;

/**
 * PlaneModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneModelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastModels()
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->orderBy('p.manufacturer', 'ASC')
            ->setMaxResults(3)
            ->getQuery();
        return $qb->getResult();
    }
}
