<?php

namespace WCS\CoavBundle\Repository;

/**
 * TerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TerrainRepository extends \Doctrine\ORM\EntityRepository
{
    const FIELDS = 'id';

    public function findLastTerrains()
    {
        $qb = $this
            ->createQueryBuilder('t')
            ->orderBy('t.city', 'ASC')
            ->setMaxResults(3)
            ->getQuery();
        return $qb->getResult();
    }
    public function findByPertinence($search, $fields)
    {
        $results = [];

    }
}
